/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache via /api/pages/publish.
 */

import { Client } from "./client";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getPage } from "../../lib/get-page";
import { getSupabaseClient } from "../../lib/supabase";
import { resolvePerLocationData } from "../../lib/resolve-per-location";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;

  return {
    title: (await getPage(path))?.root.props?.title,
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const data = await getPage(path);
  let metadata: Record<string, unknown> | undefined;

  if (!data) {
    return notFound();
  }

  if (puckPath.length >= 3) {
    const [regionSlug, citySlug, line1Slug] = puckPath;
    const supabase = getSupabaseClient();
    const { data: locationRow } = await supabase
      .from("locations")
      .select("*")
      .eq("slug->>region", regionSlug)
      .eq("slug->>city", citySlug)
      .eq("slug->>line1", line1Slug)
      .maybeSingle();
    if (locationRow) {
      metadata = {
        location: {
          id: locationRow.id,
          name: locationRow.name,
          address: locationRow.address,
          slug: locationRow.slug,
        },
      };
    }
  }

  // Resolve per-location content overrides server-side.
  // Puck's <Render> does not call resolveData, so we must resolve here.
  const resolvedData =
    metadata?.location && typeof (metadata.location as Record<string, unknown>).id === "string"
      ? await resolvePerLocationData(data, (metadata.location as Record<string, unknown>).id as string)
      : data;

  return <Client data={resolvedData} metadata={metadata} />;
}

// Force Next.js to produce static pages: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
// Delete this if you need dynamic rendering, such as access to headers or cookies
export const dynamic = "force-static";
